### ISSUE TITLE
rxdart version is outdated

### ISSUE THREAD

**Issue by colin-lear-at-vetchip** [NordicSemiconductor/Flutter-nRF-Connect-Device-Manager#10]
Relies on rxdart version ^0.26.0 which is over 2 years old. Pls update to ^0.27.1 or latest.

**Comment by NickKibish** [comment]
Dependencies were updated in [this release](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/releases/tag/0.1.2).
