### ISSUE TITLE
dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by nissaba** [NordicSemiconductor/Flutter-nRF-Connect-Device-Manager#11]
Specs satisfying the `mcumgr_flutter (from `.symlinks/plugins/mcumgr_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.

It would be good to add in the information page what OS are supported.

**Comment by NickKibish** [comment]
I home [this](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/tree/master#supported-platforms) will help you.
