### ISSUE TITLE
Failed to parse manifest.json

### ISSUE THREAD

**Issue by david0352721** [NordicSemiconductor/Flutter-nRF-Connect-Device-Manager#54]
I use example to update my device and got this error.
I check my manifest.json, i find my manifest no "imageIndex" key, is it required need?

![截圖 2024-01-16 下午5 36 30](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/assets/46767862/8affe9e7-82f7-4518-85c4-5b1c1b02509d)

**Comment by NickKibish** [comment]
Hi @david0352721 ,
You're right; for single-core devices, it's not required and should be 0 by default.

I'll fix it.
