### ISSUE TITLE
When project imports mcumgr_flutter, iOS requests for Bluetooth permissions at startup

### ISSUE THREAD

**Issue by olo95** [NordicSemiconductor/Flutter-nRF-Connect-Device-Manager#86]
Should it be requested when methods of the plugin are in use?

**Comment by NickKibish** [comment]
You're absolutely correct.

The Bluetooth permissions issue you've raised was indeed addressed following a request in #81, and it's been resolved in version [0.4.1](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/releases/tag/0.4.1). 

To see the fix in action, you can refer to this [demo project](https://github.com/NickKibish/McuMgr-Simplest-Demo/blob/2f73dbbc4395633b42eecb68263a93794f45ceb8/lib/main.dart#L38). Let me know if you need further assistance!

**Comment by olo95** [comment]
Sorry, completely forgot to upgrade, 0.4.1 changed approach to my problem. Thank you for quick response :)
