### ISSUE TITLE
A problem occurred configuring project ':mcumgr_flutter'

### ISSUE THREAD

**Issue by anhvu2503** [NordicSemiconductor/Flutter-nRF-Connect-Device-Manager#88]
When I add dependency with mcumgr_flutter version: ^0.4.1
It was showing error like this with android
![image](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/assets/167390611/71ca9982-3315-4f6a-8a23-37a56b4ec86e)

**Comment by NickKibish** [comment]
Try to run the project from Android Studio to get a more specific error message.

In my case, it was an incompatible Kotlin version. 
![Screenshot 2024-06-24 at 20 35 16](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/assets/4790759/43bb5fe5-8991-44b0-b0d3-b22a2cf076f8)

**Comment by anhvu2503** [comment]
This is my bug
![image](https://github.com/NordicSemiconductor/Flutter-nRF-Connect-Device-Manager/assets/167390611/cc507321-1bbb-44e0-8e22-8ffd6e75e4dd)

**Comment by anhvu2503** [comment]
@MichaelQun 
You should download the library locally, place it in a specific folder, and reference the path to the folder where the library is stored.
This will resolve the issue.
